FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

ENV PYTHONPATH=/app

COPY model_pipeline /app/model_pipeline
COPY settings.py /app/settings.py
COPY .env /app/.env
EXPOSE 8000

CMD ["uvicorn", "model_pipeline.main:app", "--host", "0.0.0.0", "--port", "8000"]
